# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'M\xc3\xb3dulo')),
                ('index_max', models.PositiveIntegerField(verbose_name=b'Indice M\xc3\xa1ximo')),
                ('index_sync', models.PositiveIntegerField(verbose_name=b'Resincronizaci\xc3\xb3n')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'M\xf3dulo',
                'verbose_name_plural': 'M\xf3dulos',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.PositiveIntegerField(verbose_name=b'Num de Comando')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre Comando')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claves.Board')),
            ],
            options={
                'ordering': ['board', 'command'],
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Empresa')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Placa o Num Eco')),
                ('nip', models.PositiveIntegerField(verbose_name=b'NIP')),
                ('mask', models.PositiveIntegerField(verbose_name=b'Num Lote')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claves.Board')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claves.Customer')),
            ],
            options={
                'ordering': ['board', 'customer', 'name'],
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('board', 'customer', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([('board', 'command')]),
        ),
    ]
